#!/bin/bash

# refer  spf13-vim bootstrap.sh`
BASEDIR=$(dirname $0)
cd $BASEDIR
CURRENT_DIR=`pwd`

# parse arguments
function show_help
{
    echo "install.sh [option]
    --for-vim       Install configuration files for vim, default option
    --for-neovim    Install configuration files for neovim
    --for-all       Install configuration files for vim & neovim
    --help          Show help messages
For example:
    install.sh --for-vim
    install.sh --help"
}
FOR_VIM=true
FOR_NEOVIM=false
if [ "$1" != "" ]; then
    case $1 in
        --for-vim)
            FOR_VIM=true
            FOR_NEOVIM=false
            shift
            ;;
        --for-neovim)
            FOR_NEOVIM=true
            FOR_VIM=false
            shift
            ;;
        --for-all)
            FOR_VIM=true
            FOR_NEOVIM=true
            shift
            ;;
        *)
            show_help
            exit
            ;;
    esac
fi

lnif() {
    if [ -e "$1" ]; then
        ln -sf "$1" "$2"
    fi
}


echo "Step1: backing up current vim config"
today=`date +%Y%m%d`
if $FOR_VIM; then
    for i in $HOME/.vim $HOME/.vimrc $HOME/.gvimrc $HOME/.vimrc.bundles; do [ -e $i ] && [ ! -L $i ] && mv $i $i.$today; done
    for i in $HOME/.vim $HOME/.vimrc $HOME/.gvimrc $HOME/.vimrc.bundles; do [ -L $i ] && unlink $i ; done
fi
if $FOR_NEOVIM; then
    for i in $HOME/.config/nvim $HOME/.config/nvim/init.vim; do [ -e $i ] && [ ! -L $i ] && mv $i $i.$today; done
    for i in $HOME/.config/nvim/init.vim $HOME/.config/nvim; do [ -L $i ] && unlink $i ; done
fi

echo "Step2: setting up symlinks"
if $FOR_VIM; then
    lnif $CURRENT_DIR/vimrc $HOME/.vimrc
    lnif $CURRENT_DIR/vimrc.bundles $HOME/.vimrc.bundles
    lnif "$CURRENT_DIR/" "$HOME/.vim"
fi
if $FOR_NEOVIM; then
    lnif "$CURRENT_DIR/" "$HOME/.config/nvim"
    lnif $CURRENT_DIR/vimrc $CURRENT_DIR/init.vim
fi
SCRIPTS_DIR=$CURRENT_DIR/scripts
function install_scripts()
{
    local src_dir=$1
    local dst_dir=$HOME/.vim
    #local dst_dir=$CURRENT_DIR/others

    ls $src_dir/*.tar.gz 2>/dev/null 1>/dev/null
    if [ $? -eq 0 ]
    then
        tar -xzvf $src_dir/*.tar.gz -C $dst_dir
        ls -shl $src_dir/*.tar.gz
    fi

    ls $src_dir/*.tar.bz2  2>/dev/null 1>/dev/null
    if [ $? -eq 0 ]
    then
        tar -xjvf $src_dir/*.tar.bz2 -C $dst_dir
        ls -shl $src_dir/*.tar.bz2
    fi

    ls $src_dir/*.tar 2>/dev/null 1>/dev/null
    if [ $? -eq 0 ]
    then
        tar -xvf $src_dir/*.tar -C $dst_dir
        ls -shl $src_dir/*.tar
    fi

    ls $src_dir/*.zip 2>/dev/null 1>/dev/null
    if [ $? -eq 0 ]
    then
        #由于unzip不支持正则,我们使用xargs作为辅助
        ls $src_dir/*.zip | xargs -i -d "\n" unzip {} -d $dst_dir
        ls -shl $src_dir/*.zip
    fi

    ls $src_dir/*.vim 2>/dev/null 1>/dev/null
    if [ $? -eq 0 ]
    then
        cp -v $src_dir/*.vim $dst_dir/plugin
        ls -shl $src_dir/*.vim
    fi

    return 0
}
echo "vimtools: addition"
today=`date +%Y%m%d`
install_scripts $SCRIPTS_DIR


echo "Step3: update/install plugins using Vim-plug"
system_shell=$SHELL
export SHELL="/bin/sh"
if $FOR_VIM; then
    vim -u $HOME/.vimrc.bundles +PlugInstall! +PlugClean! +qall
else
    nvim -u $HOME/.vimrc.bundles +PlugInstall! +PlugClean! +qall
fi
export SHELL=$system_shell


echo "Step4: compile YouCompleteMe"
echo "It will take a long time, just be patient!"
echo "If error,you need to compile it yourself"
echo "cd $CURRENT_DIR/bundle/YouCompleteMe/ && python install.py --clang-completer"
cd $CURRENT_DIR/bundle/YouCompleteMe/
git submodule update --init --recursive
if [ `which clang` ]   # check system clang
then
    python install.py --clang-completer --system-libclang   # use system clang
else
    python install.py --clang-completer
fi

echo "Install Done!"
